export const cvSkills: Record<string, string[]> = {
  Languages: ['JavaScript', 'TypeScript', 'Python', 'Java'],
  'Mobile & Frontend': [
    'React Native',
    'Expo',
    'React.js',
    'Next.js',
    'Angular',
    'Redux',
    'Zustand',
  ],
  'Backend & Data': ['Node.js', 'Express', 'MySQL', 'MongoDB', 'Supabase'],
  'Cloud & Infrastructure': [
    'AWS CDK',
    'ECS Fargate',
    'Lambda',
    'RDS / Aurora',
    'API Gateway',
    'SQS',
    'CloudWatch',
    'WAF',
    'VPC',
  ],
  'DevOps & Quality': [
    'GitHub Actions',
    'Docker',
    'NGINX',
    'Sentry',
    'SonarQube',
    'Expo EAS',
  ],
  'Leadership & Process': [
    'Team Leadership',
    'Hiring & Onboarding',
    'Engineering Mentoring',
    'Async Communication',
    'Documentation-First Workflows',
    'Distributed Team Coordination',
    'Agile / Scrum',
    'Stakeholder Management',
    'Code Review',
  ],
};
