export const cvSkills: Record<string, string[]> = {
  'Leadership & Process': [
    'Technical Architecture',
    'Team Leadership',
    'Agile / Scrum',
    'Code Review',
    'Stakeholder Management',
    'Engineering Mentoring',
  ],
  'Cloud & Infrastructure': [
    'AWS CDK',
    'ECS Fargate',
    'Lambda',
    'RDS / Aurora',
    'API Gateway',
    'SQS',
    'EventBridge',
    'WAF',
    'VPC',
    'CloudWatch',
    'CloudFormation',
  ],
  'DevOps & Quality': [
    'GitHub Actions',
    'Docker',
    'NGINX',
    'Sentry',
    'SonarQube',
    'Expo EAS',
    'Cloudflare',
  ],
  'Mobile & Frontend': [
    'React Native',
    'Expo',
    'React.js',
    'Next.js',
    'Angular',
    'Redux',
    'Zustand',
    'Tailwind CSS',
  ],
  'Backend & Data': ['Node.js', 'Express', 'MySQL', 'MongoDB', 'Supabase'],
  Testing: ['Jest', 'Playwright', 'Cypress', 'Maestro', 'Jasmine'],
  Payments: ['Stripe', 'Adyen', 'Airwallex', 'Terminal Integration'],
  Languages: ['JavaScript', 'TypeScript', 'Python', 'Java'],
};
